INCLUDE(${PROJECT_SOURCE_DIR}/user111.cmake)

SET(ENV{PATH} c:/mingw/bin c:/mingw/msys/1.0/bin)

#SET(CMAKE_SYSTEM_NAME 	Windows)
#SET(CMAKE_C_COMPILER 	gcc)
#SET(CMAKE_CXX_COMPILER 	g++)

#SET(CMAKE_FIND_ROOT_PATH  C:/MinGW)

#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)